name: setup-java-gradle
description: Setup java, gradle, and naively cache gradle directories

inputs:
  java-version:
    description: Which Java Version
    required: false
    default: "21"
  distribution:
    description: Which Java Distribution
    required: false
    default: "temurin"
  writeable:
    description: Treat the cache as writeable
    required: false
    default: "false"
  gradle-job-summary:
    description: Specifies when a Job Summary should be inluded in the action results. Valid values are 'never', 'always' (default), and 'on-failure'.
    required: false
    default: "always"
  gradle-job-summary-as-pr-comment:
    description: Specifies when each Job Summary should be added as a PR comment. Valid values are 'never' (default), 'always', and 'on-failure'. No action will be taken if the workflow was not triggered from a pull request.
    required: false
    default: "never"
  gradle-dependency-graph:
    description: The gradle action dependency graph value (disabled,generate,generate-and-submit,generate-submit-and-upload,generate-and-upload,download-and-submit)
    required: false
    default: "disabled"

runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
    - name: Dependency Submission Decision
      id: submission
      shell: bash
      env:
        CACHE_WRITEABLE: ${{ inputs.writeable }}
        DEPENDENCY_GRAPH_REQUEST: ${{ inputs.gradle-dependency-graph }}
      run: |
        create_graph() {
          if [[ "$CACHE_WRITEABLE" == "true" || "$CACHE_WRITEABLE" == "yes" ]]; then
            if [[ "$DEPENDENCY_GRAPH_REQUEST" == "disabled" ]]; then
              return 0
            fi
          fi
          return 1
        }
        if create_graph; then
          echo "dependency_submission=generate-and-submit" >>"$GITHUB_OUTPUT"
        else
          echo "dependency_submission=$DEPENDENCY_GRAPH_REQUEST" >>"$GITHUB_OUTPUT"
        fi
    - name: Setup Gradle
      id: setup_gradle
      uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
      with:
        gradle-version: wrapper
        dependency-graph: ${{ steps.submission.outputs.dependency_submission }}
        add-job-summary: ${{ inputs.gradle-job-summary }}
        add-job-summary-as-pr-comment: ${{ inputs.gradle-job-summary-as-pr-comment}}
        cache-disabled: true
    - name: Configure Gradle
      id: gradle_cache_lifetime
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: |
        mkdir -p ~/.gradle/init.d
        cp -f "${ACTION_PATH}/cache-settings.init.gradle" ~/.gradle/init.d/cache-settings.init.gradle

    - name: ReadOnly Cache
      uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      if: inputs.writeable != 'yes' && inputs.writeable !='true'
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties','buildSrc/**/Versions.kt', 'buildSrc/**/Dependencies.kt', 'gradle/*.versions.toml', '**/versions.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Cache
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      id: rw-plugin-cache
      if: inputs.writeable == 'yes' || inputs.writeable =='true'
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties','buildSrc/**/Versions.kt', 'buildSrc/**/Dependencies.kt', 'gradle/*.versions.toml', '**/versions.properties') }}
        restore-keys: ${{ runner.os }}-gradle-
