version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "03:11"
      timezone: "Europe/London"
    allow:
      - dependency-type: all
    commit-message:
      prefix: "deps(ci): "
  - package-ecosystem: github-actions
    directories:
      - "commit-status-and-label"
      - "default-updatecli"
      - "dependabot-merge"
      - "docker-image-builder"
      - "pr-or-issue-comment"
      - "pr-trigger"
      - "repo-dispatch"
      - "dismiss-dependabot-alerts"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "04:11"
      timezone: "Europe/London"
    allow:
      - dependency-type: all
    commit-message:
      prefix: "deps: "
