version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "cron"
      cronjob: "11 03 * * *"
    rebase-strategy: disabled
    cooldown:
      default-days: 3
      exclude:
        - "quotidian-ennui/*"
    allow:
      - dependency-type: all
    commit-message:
      prefix: "deps(ci): "
    groups:
      workflows-olio:
        patterns:
          - "quotidian-ennui/workflows-olio/*"

  - package-ecosystem: github-actions
    directories:
      - "commit-status-and-label"
      - "default-updatecli"
      - "dependabot-merge"
      - "docker-image-builder"
      - "pr-or-issue-comment"
      - "pr-trigger"
      - "repo-dispatch"
      - "dismiss-dependabot-alerts"
      - "setup-java-gradle"
      - "semver-diff"
    open-pull-requests-limit: 20
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "11 04 * * *"
    allow:
      - dependency-type: all
    commit-message:
      prefix: "deps: "
    cooldown:
      default-days: 4
      exclude:
        - "quotidian-ennui/*"
    groups:
      workflows-olio:
        patterns:
          - "quotidian-ennui/workflows-olio/*"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "gradle"
    directory: "src/test/setup-java-gradle"
    open-pull-requests-limit: 20
    rebase-strategy: disabled
    cooldown:
      default-days: 4
    schedule:
      interval: "cron"
      cronjob: "23 04 * * *"
    allow:
      - dependency-type: "all"
    groups:
      setup-java-test:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directories:
      - "src/test/docker-image-builder"
    open-pull-requests-limit: 20
    rebase-strategy: disabled
    cooldown:
      default-days: 4
    schedule:
      interval: "cron"
      cronjob: "23 03 * * *"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "ubi10"
        versions:
          - ">=11.0"
