name: dependabot-action-merge
description: |
  Use dependabot-merge instead.
inputs:
  token:
    description: The github token to use when committing changes
    required: false
    default: ${{ github.token }}
  automerge_level:
    description: |
      The semver level to allow automerge up to (default semver-patch|semver-minor).
    required: false
    default: "semver-patch|semver-minor"

runs:
  using: composite
  steps:
    - name: warning
      id: warning
      shell: bash
      run: |
        echo "::warning::dependabot-action-merge is deprecated, use dependabot-merge instead; may be removed w/o warning"

    - name: Update PR
      id: comment
      uses: quotidian-ennui/actions-olio/dependabot-merge@main
      with:
        token: ${{ inputs.token }}
        automerge_level: ${{ inputs.automerge_level }}
        change_filter: ".github/workflows/**"
