name: pr-trigger
description: |
  Create a repository dispatch event for a PR.
inputs:
  event_type:
    description: The type of event to dispatch
    required: false
    default: pr-trigger
  token:
    description: The github token to use when issuing the repository dispatch
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Find associated PR
      uses: jwalton/gh-find-current-pr@89ee5799558265a1e0e31fab792ebb4ee91c016b # v1.3.3
      id: findpr
      with:
        github-token: ${{ inputs.token }}
        state: open
        sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
    - name: Grab Dependabot metadata
      if: ${{ github.actor == 'dependabot[bot]' }}
      id: depbot-metadata
      continue-on-error: true
      uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0
    - name: dispatch
      id: dispatch
      uses: quotidian-ennui/actions-olio/repo-dispatch@main
      with:
        event_type: "${{ inputs.event_type }}"
        token: ${{ inputs.token }}
        sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
        ref: ${{ github.head_ref }}
        event_detail: |
          {
            "pull_request": "${{ steps.findpr.outputs.pr }}",
            "dependabot_update_type": "${{ steps.depbot-metadata.outputs.update-type || 'unknown' }}"
          }
