name: pr-trigger
description: |
  Create a repository dispatch event for a PR.
inputs:
  event_type:
    description: The type of event to dispatch
    required: false
    default: pr-trigger
  token:
    description: The github token to use when issuing the repository dispatch
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Find associated PR
      uses: jwalton/gh-find-current-pr@7ada613939e2a233c83a1320679446fa1c6bdcb9 # v1.3.2
      id: findpr
      with:
        github-token: ${{ inputs.token }}
        state: open
        sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
    - name: Grab Dependabot metadata
      if: ${{ github.actor == 'dependabot[bot]' }}
      id: depbot-metadata
      continue-on-error: true
      uses: dependabot/fetch-metadata@c9c4182bf1b97f5224aee3906fd373f6b61b4526 # v1.6.0
    - name: dispatch
      id: dispatch
      uses: quotidian-ennui/actions-olio/repo-dispatch@main
      with:
        event_type: "${{ inputs.event_type }}"
        token: ${{ inputs.token }}
        sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
        ref: ${{ github.head_ref }}
        event_detail: |
          {
            "pull_request": "${{ steps.findpr.outputs.pr }}",
            "dependabot_update_type": "${{ steps.depbot-metadata.outputs.update-type || 'unknown' }}"
          }
