name: Docker Build
description: Build and optionally publish an image.
inputs:
  cache_from:
    description: "List of external cache sources for build-push-action (e.g., user/app:cache, type=local,src=path/to/dir)"
    required: false
  cache_to:
    description: "List of cache export destinations for build-push-action (e.g., user/app:cache, type=local,dest=path/to/dir)"
    required: false
  registry_push:
    description: Whether to push to the registry
    required: false
    default: "false"
  load_locally:
    description: Whether to load the image locally if you want to use it in a later step
    required: false
    default: "false"
  dockerfile:
    description: Path to the dockerfile
    required: true
  image_tag_suffix:
    description: Suffix for the image name
    required: false
    default: ""
  image_platforms:
    description: Platforms to build for
    required: false
    default: "linux/amd64"
  ghcr_image_name:
    description: Github container registry image name (ghcr.io/x/y/z)
    required: false
  dockerhub_image_name:
    description: Dockerhub image name
    required: false
  ghcr_user:
    description: Github container registry username
    required: false
  ghcr_token:
    description: Token for the github container registry
    required: false
  dockerhub_user:
    description: Dockerhub username
    required: false
  dockerhub_token:
    description: Dockerhub token
    required: false
outputs:
  image_tags:
    description: Docker tags
    value: ${{ steps.docker_meta.outputs.tags }}
  labels:
    description: Docker labels
    value: ${{ steps.docker_meta.outputs.labels }}
  version:
    description: Docker image version
    value: ${{ steps.docker_meta.outputs.version }}
  json:
    description: JSON output of tags and labels
    value: ${{ steps.docker_meta.outputs.json }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3.4.0
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0
    - name: Login to DockerHub
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      if: |
        inputs.registry_push == 'true' &&
        inputs.dockerhub_user != '' &&
        inputs.dockerhub_token != ''
      with:
        username: ${{ inputs.dockerhub_user }}
        password: ${{ inputs.dockerhub_token }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      if: |
        inputs.registry_push == 'true' &&
        inputs.ghcr_user != '' &&
        inputs.ghcr_token != ''
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr_user }}
        password: ${{ inputs.ghcr_token }}
    - name: Docker Image Metadata
      id: docker_meta
      uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
      with:
        images: |
          ${{ inputs.ghcr_image_name }}
          ${{ inputs.dockerhub_image_name }}
        flavor: |
          latest=auto
          suffix=${{ inputs.image_tag_suffix }},onlatest=true
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=pr,priority=100
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Build Image
      uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6.14.0
      with:
        # no-cache: true
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.image_platforms }}
        push: ${{ inputs.registry_push }}
        load: ${{ inputs.load_locally }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        provenance: false
        cache-from: ${{ inputs.cache_from }}
        cache-to: ${{ inputs.cache_to }}
