name: Docker Build
description: Build and optionally publish an image.
inputs:
  registry_push:
    description: Whether to push to the registry
    required: false
    default: "false"
  load_locally:
    description: Whether to load the image locally if you want to use it in a later step
    required: false
    default: "false"
  dockerfile:
    description: Path to the dockerfile
    required: true
  image_tag_suffix:
    description: Suffix for the image name
    required: false
    default: ""
  image_platforms:
    description: Platforms to build for
    required: false
    default: "linux/amd64"
  ghcr_image_name:
    description: Github container registry image name (ghcr.io/x/y/z)
    required: false
  dockerhub_image_name:
    description: Dockerhub image name
    required: false
  ghcr_user:
    description: Github container registry username
    required: false
  ghcr_token:
    description: Token for the github container registry
    required: false
  dockerhub_user:
    description: Dockerhub username
    required: false
  dockerhub_token:
    description: Dockerhub token
    required: false
outputs:
  image_tags:
    description: Docker tags
    value: ${{ steps.docker_meta.outputs.tags }}
  labels:
    description: Docker labels
    value: ${{ steps.docker_meta.outputs.labels }}
  version:
    description: Docker image version
    value: ${{ steps.docker_meta.outputs.version }}
  json:
    description: JSON output of tags and labels
    value: ${{ steps.docker_meta.outputs.json }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # v3.1.0
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
    - name: Login to DockerHub
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      if: |
        inputs.registry_push == 'true' &&
        inputs.dockerhub_user != '' &&
        inputs.dockerhub_token != ''
      with:
        username: ${{ inputs.dockerhub_user }}
        password: ${{ inputs.dockerhub_token }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      if: |
        inputs.registry_push == 'true' &&
        inputs.ghcr_user != '' &&
        inputs.ghcr_token != ''
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr_user }}
        password: ${{ inputs.ghcr_token }}
    - name: Docker Image Metadata
      id: docker_meta
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
      with:
        images: |
          ${{ inputs.ghcr_image_name }}
          ${{ inputs.dockerhub_image_name }}
        flavor: |
          latest=auto
          suffix=${{ inputs.image_tag_suffix }},onlatest=true
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=pr,priority=100
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Build Image
      uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6.3.0
      with:
        # no-cache: true
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.image_platforms }}
        push: ${{ inputs.registry_push }}
        load: ${{ inputs.load_locally }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        provenance: false
