# Essentially wraps makeshift/generate-dependabot-glob-action
name: Regenerate Dependabot Config
description: |-
  Regenerate dependabot configuration file and create a pull request with the changes.
inputs:
  token:
    description: Override the default token used to create the resulting PR
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Archive dependabot.yml
      id: depbot_archive
      shell: bash
      run: |
        DBOT_ORIGINAL=$(mktemp --tmpdir="$RUNNER_TEMP" "depbot-XXXXXXXX")
        cat "${{ github.workspace }}/.github/dependabot.yml" > "$DBOT_ORIGINAL"
        echo "dbot_yml_orig=$DBOT_ORIGINAL" >> "$GITHUB_OUTPUT"
    - name: Generate dependabot.yml
      uses: makeshift/generate-dependabot-glob-action@5cd45385ce6519f68d574aab9699832b3a5e5031 # v1.3.4
    - name: prettify
      uses: actionsx/prettier@3d9f7c3fa44c9cb819e68292a328d7f4384be206 # v3
      with:
        args: --write ./.github/dependabot.yml
    - name: Dependabot Change Highlights
      id: highlight
      shell: bash
      run: |
        ORIGINAL_CONFIG_DIRS=$(mktemp --tmpdir="$RUNNER_TEMP" "depbot-XXXXXXXX")
        CHANGED_CONFIG_DIRS=$(mktemp --tmpdir="$RUNNER_TEMP" "depbot-XXXXXXXX")
        yq eval '.updates[].directory' < "${{ steps.depbot_archive.outputs.dbot_yml_orig }}" | sort -u > "${ORIGINAL_CONFIG_DIRS}"
        yq eval '.updates[].directory' < "${{ github.workspace }}/.github/dependabot.yml" | sort -u > "${CHANGED_CONFIG_DIRS}"
        first_diff=$(basename "$(comm -3 "${ORIGINAL_CONFIG_DIRS}" "${CHANGED_CONFIG_DIRS}" | head -n 1 | sed -e 's/^[[:blank:]]*//' -e 's/[[:blank:]]*$//')")
        echo "commit_msg=feat(ci): update dependabot config ($first_diff)" >> "$GITHUB_OUTPUT"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
      with:
        commit-message: "${{ steps.highlight.outputs.commit_msg }}"
        branch: feature/ci-update-dependabot-config-${{ hashFiles('**/dependabot.yml') }}
        title: "${{ steps.highlight.outputs.commit_msg }}"
        token: ${{ inputs.token }}
        body: |
          Dependabot config has been updated by [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
