name: Repository Dispatch Event
description: |-
  Sends a semi-standardised repo-dispatch event using peter-evans/repository-dispatch
inputs:
  event_type:
    description: Used as the event_type in the dispatch event
    required: true
  token:
    description: Override the default token used to create the dispatch event.
    required: false
    default: ${{ github.token }}
  repository:
    description: Override the default repository you want to send to
    required: false
    default: ${{ github.repository }}
  sha:
    description: Override github.event.client_payload.base.sha with your own value
    required: false
  ref:
    description: Override github.event.client_payload.base.ref with your own value
    required: false
  actor:
    description: Override github.event.client_payload.base.actor with your own value
    required: false
    default: ${{ github.actor }}
  event_detail:
    description: Add data as github.event.client_payload.detail
    required: false

runs:
  using: composite
  steps:
    - name: Dispatch Event
      id: dispatch
      uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2.1.2
      with:
        event-type: ${{ inputs.event_type }}
        client-payload: |-
          {
            "repository" : "${{ github.repository }}",
            "base" : {
              "event_trigger" : "${{ github.event_name }}",
              "workflow" : "${{ github.workflow }}",
              "workflow_run_url" : "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "actor" : "${{ inputs.actor }}",
              "ref" : "${{ inputs.ref || github.head_ref || github.ref }}",
              "sha": "${{ inputs.sha || github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}"
            },
            "detail": ${{ inputs.event_detail|| '{}' }}
          }
