name: Check PR
on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  committed:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: |
      github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: committed
        uses: crate-ci/committed@e0a4ba358ac0e6292e750f61b74f77a347eb10ad # v1.0.20
        with:
          args: --no-merge-commit

  dependabot-merge:
    needs:
      - committed
    permissions:
      contents: write
      pull-requests: write
    if: |
      github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Find associated PR
        uses: jwalton/gh-find-current-pr@7ada613939e2a233c83a1320679446fa1c6bdcb9 # v1.3.2
        id: findpr
        with:
          github-token: ${{ github.token }}
          state: open
          sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
      - name: merge-if-built
        continue-on-error: true
        uses: fastify/github-action-merge-dependabot@59fc8817458fac20df8884576cfe69dbb77c9a07 # v3.9.1
        with:
          pr-number: ${{ steps.findpr.outputs.pr }}
          target: minor
