name: Debug Repo Dispatch
run-name: Debug (${{ github.event.action }})

on:
  repository_dispatch:


permissions: {}

jobs:
  debug:
    name: "Debug"
    runs-on: ubuntu-latest
    steps:
      - name: Debug Env & Event
        uses: hmarr/debug-action@cd1afbd7852b7ad7b1b7a9a1b03efebd3b0a1820 # v3.0.0
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
