name: Regenerate Dependabot Config

on:
  push:
    branches:
      - main
    paths:
      - "**/action.yml"
      - "**/Dockerfile"
      - ".github/dependabot.template.yml"
  workflow_dispatch:


defaults:
  run:
    shell: bash

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  regenerate-dependabot-yml:
    name: Regenerate Dependabot yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: generate-dependabot-config
        uses: ./generate-dependabot-config