name: test-docker-image-builder

on:
  push:
    paths:
      - "docker-image-builder/**"
      - ".github/workflows/test-docker-image-builder.yml"
  pull_request:
    branches:
      - main
    paths:
      - "docker-image-builder/**"
      - ".github/workflows/test-docker-image-builder.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test-docker-image-builder:
    name: test-docker-image-builder
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: step-security/harden-runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: docker-image-builder
        id: docker
        uses: ./docker-image-builder
        with:
          registry_push: false
          dockerfile: docker-image-builder/Dockerfile.test
          image_platforms: linux/amd64
          dockerhub_image_name: ${{ github.repository_owner }}/test-docker-image-builder
      - name: Use the image
        id: docker_run
        # bash + curl installed as part of docker-image-builder/Dockerfile.test
        run: |
          docker run --rm \
            --entrypoint=bash ${{ github.repository_owner }}/test-docker-image-builder:latest \
            -c "curl -fSsL https://raw.githubusercontent.com/${{ github.repository }}/main/README.md"
