name: test-setup-java

on:
  push:
    branches:
      - main
    paths:
      - "setup-java-gradle/**"
      - ".github/workflows/test-setup-java.yml"
  pull_request:
    branches:
      - main
    paths:
      - "setup-java-gradle/**"
      - ".github/workflows/test-setup-java.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test-setup-java:
    name: test-setup-java
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: step-security/harden-runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            plugins-artifacts.gradle.org:443
            plugins.gradle.org:443
            release-assets.githubusercontent.com:443
            repo.maven.apache.org:443

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: setup-java
        id: setup-java
        uses: ./setup-java-gradle
        with:
          java-version: "21"
          distribution: "temurin"
          gradle-dependency-graph: disabled
          gradle-job-summary: on-failure
          writeable: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: gradle-build
        id: gradle-build
        shell: bash
        working-directory: ./setup-java-gradle/test
        run: |
          ./gradlew check

  notification:
    name: notification
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - test-setup-java
    if: |
      github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: dispatch
        uses: ./pr-trigger
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event_type: "pr-setup-java-gradle-test-success"
